### ISSUE TITLE
R16B support

### ISSUE THREAD

**Issue by dch** [rabbitmq/erlando#13]
Clearly erlando relies on pmods. Are you intending to release an R16B - compatible version in future?

**Comment by arcusfelis** [comment]
In case someone is still using erlando.
I created a version without pmods and without pmods parse transform.
https://github.com/mad-cocktail/erlando

**Comment by michaelklishin** [comment]
We should transfer main repo over to you then. Need to clarify with legal first.

**Comment by lemenkov** [comment]
I believe this ticket should be closed, since the issue was addressed in PR #17.
