### ISSUE TITLE
use of parameterized modules?

### ISSUE THREAD

**Issue by etnt** [rabbitmq/erlando#15]
The docs indicates the parameterized modules functionality is required but
that has been removed from Erlang (I believe) so what does that mean?
Is erlando non-functional nowadays?

**Comment by dumbbell** [comment]
Hi!

`erlando` is now unmaintained. We should probably add a note in the `README.md`.

**Comment by michaelklishin** [comment]
We should merge community pull requests, though.

**Comment by simonmacmullen** [comment]
We could. If someone from the community wanted to adopt erlando they'd be very welcome, though.
