### ISSUE TITLE
Time to tag new release?

### ISSUE THREAD

**Issue by lemenkov** [rabbitmq/erlando#18]
Hello All!
Is it time to tag a new release?

**Comment by michaelklishin** [comment]
We can tag a new release but Erlando is not really maintained. Would you be interested in maintaining it?

**Comment by lemenkov** [comment]
![Sorry, sorry, sorry!](http://gifrific.com/wp-content/uploads/2012/06/snow-white-run-away.gif)

I don't think I could be a good candidate for maintaining this, although I'm using it. There are lots of others persons who dedicaded much more time and energy to this library (in their forks). Let's wait - perhaps someone will step in oneday :)

**Comment by michaelklishin** [comment]
We can tag HEAD, what version should be used? (it makes no sense to follow RabbitMQ versioning for Erlando)

**Comment by lukebakken** [comment]
Team RabbitMQ considers this project abandoned and will archive this repository. Anyone can feel free to push the code to a new repo and continue maintenance. Thanks!
