### ISSUE TITLE
The syntax of cuts

### ISSUE THREAD

**Issue by ferd** [rabbitmq/erlando#2]
Given how 'cut' works and the special cases for the syntactic nesting as mentioned in https://github.com/rabbitmq/erlando/blob/bug24025/README.md, it feels to me that the cut syntax should rather be wrapped in a special function call of the form `cut(<Exp>)` as it is the case with many other parse transforms.

To explain, let's reuse your example:

```
list_to_binary([1, 2, math:pow(2, _)]).
```

This, as the text says, would yield 

```
list_to_binary([1, 2, fun (X) -> math:pow(2, X) end]).
```

 and not

```
fun (X) -> list_to_binary([1, 2, math:pow(2, X)]) end.
```

If instead the syntax was `cut(Expression)`, you could easily choose between

```
list_to_binary([1, 2, cut(math:pow(2,_))])
```

and 

```
cut(list_to_binary([1, 2, math:pow(2, _)])). 
```

You could also increase the flexibility of patterns such as 

```
 F = [1, _, _, [_], 5, 6, [_], _]
 [1, 2, 3, G, 5, 6, H, 8] = F(2, 3, 8),
```

Now possibly being

```
F = cut([1, _, _, [_], 5, 6, [_], _])
[1, 2, 3, [4], 5, 6, [7], 8] = F(2,3,4,7,8)
```

Which seems rather tedious to do with the current syntax.

Other advantages would include a better fit with currently existing parse transforms. The best example of this is for QLC, where instead of basing the parse transform on its context in order to do things, you simply wrap the list comprehension in a `qlc:q(LC)` call, or ets' fun2ms where you do `ets:fun2ms(Fun)`. In this last case, it also allows the code to have special cases for shell functions (whose internal structure is more like abstract code) to be able to turn them into match specifications transparently.

Given the advice of some Erlangers on IRC, wrapping things in a `cut(Exp)` call also makes it easier to parse visually, denotes intent better, is more flexible and serves as a warning sign that magic is happening at this place (and it's not an error!). Without having too much experience with parse transform myself, I will make the audacious call that it might make things easier to parse in the first place for the parse transform, but I might well be wrong on that one, especially since the code has already been written.

Note that this view also aligns better with the Scheme implementation it is inspired by, given the scheme implementation uses a special `(cut <exp>)` syntax to wrap its use.

**Comment by jkrukoff** [comment]
For anybody else who stumbles on this issue, here's my attempt at implementing a cut/cute wrapper in order to resolve the above: https://github.com/jkrukoff/partial

**Comment by lukebakken** [comment]
Team RabbitMQ considers this project abandoned and will archive this repository. Anyone can feel free to push the code to a new repo and continue maintenance. Thanks!
